services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    env_file:
      - ./apps/server/.env.development
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis/data

  adminer:
    image: adminer:latest
    container_name: adminer_container
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DEFAULT_DB=${POSTGRES_DATABASE}
      - ADMINER_DEFAULT_USER=${POSTGRES_USER}
      - ADMINER_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
      - ADMINER_DESIGN=pepa-linha
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 10s
      retries: 3

  backend:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./apps/server:/app

volumes:
  postgres-data:
  redis-data:
