import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "normalize.css";
import "@/assets/styles/globals.css";
import { ThemeProvider } from "@/components/ThemeProvider/ThemeProvider";
import { Toaster } from "sonner";
import { Provider } from "@/components/ReactQuery/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider>
          <ThemeProvider>{children}</ThemeProvider>
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
